### ISSUE TITLE
Cloning into another database

### ISSUE THREAD

**Issue by icsStudentAcc** [BKWLD/cloner#4]
Hello,
I am trying to clone into another database. 
`$duplicate = Ticket::where('id',$id)->first()->setConnection('mysql2')->duplicate();` 
but it will not duplicate into the other database and duplicates to the default database. Please tell me how I can duplicate into another database.

**Comment by weotch** [comment]
Huh! I never considered doing that.  I used Laravel's `replicate` to do the cloning: https://laravel.com/api/5.2/Illuminate/Database/Eloquent/Model.html#method_replicate.  And then a normal `save()`.  That may help you look into it further and submit a PR.

**Comment by weotch** [comment]
Looks like Laravel has some issues with relationships and multiple database connections: https://github.com/laravel/framework/issues/9355.  Looking more into this...
