### ISSUE TITLE
Any way to get original id using onCloning function?

### ISSUE THREAD

**Issue by ArturSubotkevic** [BKWLD/cloner#6]
The thing is, that I'm cloning relationships of relationships of relationships...

I'm using `onCloning` function to set up correct parent_id's.

I'm trying to save `original_id` and `original_parent_id` using `onCloning` function. But in this function I'm not able to get original id of clonable model.

Any thoughts?

**Comment by weotch** [comment]
I see you closed, but just in case anyone else finds this, the callbacks now return the original model.  So it would be:

```php
public function onCloning($src) {
  echo $src->getKey(); // or $src->id;
}
```

This functionality is currently only in `master`, but will be tagged into `2.1.0` today or tomorrow.
