### ISSUE TITLE
Cloneable undefined

### ISSUE THREAD

**Issue by mikewink** [BKWLD/cloner#7]
Hello, I'm running Laravel 5.4 and for some reason the classes are not picked up.

I installed as normal via composer and it worked. I then add the following to `app.php` in config:
```php
// app.php
…
'providers' => [
  …
  Bkwld\Cloner\ServiceProvider::class,
  …
]
````
When I then add:

```php
// Option.php

<?php

namespace App;

use Eloquent;

class Option extends Eloquent {
    
    use Bkwld\Cloner\Cloneable;
```

to my model I get the following error message `Trait 'App\Bkwld\Cloner\Cloneable' not found`.

What am I doing wrong?

**Comment by weotch** [comment]
Ulp, that's a mistake in the readme where I hadn't updated it for Laravel 5 where models now all live in the `App` namespace.  I've now fixed it: https://github.com/BKWLD/cloner/commit/644ac6b6469432c29ccfd4154da192e8e9e244df

To answer your specific question, do this instead `use \Bkwld\Cloner\Cloneable;` (note the leading backslash)
