### ISSUE TITLE
Clone relationship with additional pivot data?

### ISSUE THREAD

**Issue by iolkoz-iametza** [BKWLD/cloner#8]
Hi
as I say in the title, is possible to accomplish this?
I have a morphToMany relationship and I save additional data, like in this example from the Laravel docs:

`$user->roles()->attach($roleId, ['expires' => $expires]);`

If I use the `duplicate()` function it duplicates the relationship but the additional data is not copied. 

Any ideas for this?

Thanks and great job with this package!

**Comment by weotch** [comment]
Huh, that would be nice.  It'd be a change here: https://github.com/BKWLD/cloner/blob/master/src/Cloner.php#L165-L168.  The only real challenge is figuring out how to get all the pivot values that need to be synced at the same time.

I don't see myself working on this in the short term but I'd happily take a PR for it.

**Comment by tviggyr** [comment]
User corridor provided a solution. It is possible to merge its branch?

**Comment by weotch** [comment]
I released this here, sorry for the delay: https://github.com/BKWLD/cloner/releases/tag/3.3.0
